[package]
name = "day-9"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tuple = "0.5.1"
scanf = "1.2.1"
itertools = "0.10.0"